server:
  port: 9099

spring:
  application:
    name: apigateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/

zuul:
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: authserver
    order:
      path: /board/**
      sensitiveHeaders:
      serviceId: board
  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9099/auth/oauth/token
      user-authorization-uri: http://localhost:9099/auth/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:9099/auth/user
      prefer-token-info: false

