spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: authserver

  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8
    username: root
    password: lly2018*
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 9999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/

logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3